const actions = {
    // Login actions
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    SET_STATE: "SET_STATE",
    LOGOUT: "LOGOUT",

    // Alert actions
    ALERT_SUCCESS: "ALERT_SUCCESS",
    ALERT_FAILURE: "ALERT_FAILURE",
    ALERT_CLEAR: "ALERT_CLEAR",

    // Register actions
    REGISTER_REQUEST: "REGISTER_REQUEST",
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    REGISTER_FAILURE: "REGISTER_FAILURE",

}

export default actions;