const actions = {
    // Login actions
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    SET_STATE: "SET_STATE",
    LOGOUT: "LOGOUT",

    // Alert actions
    ALERT_SUCCESS: "ALERT_SUCCESS",
    ALERT_FAILURE: "ALERT_FAILURE",
    ALERT_CLEAR: "ALERT_CLEAR",

    // Register actions
    REGISTER_REQUEST: "REGISTER_REQUEST",
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    REGISTER_FAILURE: "REGISTER_FAILURE",

    // App actions
    MINIMIZE_SIDEBAR: "MINIMIZE_SIDEBAR",
    MAXIMIZE_SIDEBAR: "MAXIMIZE_SIDEBAR",
    TOGGLE_SIDEBAR: "TOGGLE_SIDEBAR",
    TOGGLE_MENU_DISPLAY: "TOGGLE_MENU_DISPLAY",

    // Task actions
    ADD_TASK: "ADD_TASK",
    COMPLETE_TASK: "COMPLETE_TASK",
    DELETE_TASK: "DELETE_TASK",
    UPDATE_TASK: "UPDATE_TASK",
    ADDING_TASK: "ADDING_TASK",
    CLEAR_ADDING_STATE: "CLEAR_ADDING_STATE",
    TASK_INPUT_VALUE_CHANGED : "TASK_INPUT_VALUE_CHANGED",
    SET_TASKS_STATE : "SET_TASKS_STATE",
    GET_TASKS: "GET_TASKS",
    UPDATE_STATE: "UPDATE_STATE"
}

export default actions;